apiVersion: v1
kind: Service
metadata:
  name: url-shortener-service
spec:
  selector:
    app: url-shortener
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: LoadBalancer # Change this based on your network configuration